/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppWeekRouteImport } from './routes/_authenticated/app.week'
import { Route as AuthenticatedAppTodayRouteImport } from './routes/_authenticated/app.today'
import { Route as AuthenticatedAppTasksRouteImport } from './routes/_authenticated/app.tasks'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppProjectsRouteImport } from './routes/_authenticated/app.projects'
import { Route as AuthenticatedAppMonthRouteImport } from './routes/_authenticated/app.month'
import { Route as AuthenticatedAppInboxRouteImport } from './routes/_authenticated/app.inbox'
import { Route as AuthenticatedAppFocusRouteImport } from './routes/_authenticated/app.focus'
import { Route as AuthenticatedAppCategoriesRouteImport } from './routes/_authenticated/app.categories'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google.callback'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppWeekRoute = AuthenticatedAppWeekRouteImport.update({
  id: '/app/week',
  path: '/app/week',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppTodayRoute = AuthenticatedAppTodayRouteImport.update({
  id: '/app/today',
  path: '/app/today',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppTasksRoute = AuthenticatedAppTasksRouteImport.update({
  id: '/app/tasks',
  path: '/app/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/app/settings',
    path: '/app/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppProjectsRoute =
  AuthenticatedAppProjectsRouteImport.update({
    id: '/app/projects',
    path: '/app/projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppMonthRoute = AuthenticatedAppMonthRouteImport.update({
  id: '/app/month',
  path: '/app/month',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppInboxRoute = AuthenticatedAppInboxRouteImport.update({
  id: '/app/inbox',
  path: '/app/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppFocusRoute = AuthenticatedAppFocusRouteImport.update({
  id: '/app/focus',
  path: '/app/focus',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppCategoriesRoute =
  AuthenticatedAppCategoriesRouteImport.update({
    id: '/app/categories',
    path: '/app/categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/categories': typeof AuthenticatedAppCategoriesRoute
  '/app/focus': typeof AuthenticatedAppFocusRoute
  '/app/inbox': typeof AuthenticatedAppInboxRoute
  '/app/month': typeof AuthenticatedAppMonthRoute
  '/app/projects': typeof AuthenticatedAppProjectsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/tasks': typeof AuthenticatedAppTasksRoute
  '/app/today': typeof AuthenticatedAppTodayRoute
  '/app/week': typeof AuthenticatedAppWeekRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/categories': typeof AuthenticatedAppCategoriesRoute
  '/app/focus': typeof AuthenticatedAppFocusRoute
  '/app/inbox': typeof AuthenticatedAppInboxRoute
  '/app/month': typeof AuthenticatedAppMonthRoute
  '/app/projects': typeof AuthenticatedAppProjectsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/tasks': typeof AuthenticatedAppTasksRoute
  '/app/today': typeof AuthenticatedAppTodayRoute
  '/app/week': typeof AuthenticatedAppWeekRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app/categories': typeof AuthenticatedAppCategoriesRoute
  '/_authenticated/app/focus': typeof AuthenticatedAppFocusRoute
  '/_authenticated/app/inbox': typeof AuthenticatedAppInboxRoute
  '/_authenticated/app/month': typeof AuthenticatedAppMonthRoute
  '/_authenticated/app/projects': typeof AuthenticatedAppProjectsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/tasks': typeof AuthenticatedAppTasksRoute
  '/_authenticated/app/today': typeof AuthenticatedAppTodayRoute
  '/_authenticated/app/week': typeof AuthenticatedAppWeekRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/app/categories'
    | '/app/focus'
    | '/app/inbox'
    | '/app/month'
    | '/app/projects'
    | '/app/settings'
    | '/app/tasks'
    | '/app/today'
    | '/app/week'
    | '/app/'
    | '/api/public/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/app/categories'
    | '/app/focus'
    | '/app/inbox'
    | '/app/month'
    | '/app/projects'
    | '/app/settings'
    | '/app/tasks'
    | '/app/today'
    | '/app/week'
    | '/app'
    | '/api/public/google/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/_authenticated/app/categories'
    | '/_authenticated/app/focus'
    | '/_authenticated/app/inbox'
    | '/_authenticated/app/month'
    | '/_authenticated/app/projects'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/tasks'
    | '/_authenticated/app/today'
    | '/_authenticated/app/week'
    | '/_authenticated/app/'
    | '/api/public/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/week': {
      id: '/_authenticated/app/week'
      path: '/app/week'
      fullPath: '/app/week'
      preLoaderRoute: typeof AuthenticatedAppWeekRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/today': {
      id: '/_authenticated/app/today'
      path: '/app/today'
      fullPath: '/app/today'
      preLoaderRoute: typeof AuthenticatedAppTodayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/tasks': {
      id: '/_authenticated/app/tasks'
      path: '/app/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AuthenticatedAppTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/projects': {
      id: '/_authenticated/app/projects'
      path: '/app/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AuthenticatedAppProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/month': {
      id: '/_authenticated/app/month'
      path: '/app/month'
      fullPath: '/app/month'
      preLoaderRoute: typeof AuthenticatedAppMonthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/inbox': {
      id: '/_authenticated/app/inbox'
      path: '/app/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AuthenticatedAppInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/focus': {
      id: '/_authenticated/app/focus'
      path: '/app/focus'
      fullPath: '/app/focus'
      preLoaderRoute: typeof AuthenticatedAppFocusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/categories': {
      id: '/_authenticated/app/categories'
      path: '/app/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AuthenticatedAppCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppCategoriesRoute: typeof AuthenticatedAppCategoriesRoute
  AuthenticatedAppFocusRoute: typeof AuthenticatedAppFocusRoute
  AuthenticatedAppInboxRoute: typeof AuthenticatedAppInboxRoute
  AuthenticatedAppMonthRoute: typeof AuthenticatedAppMonthRoute
  AuthenticatedAppProjectsRoute: typeof AuthenticatedAppProjectsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTasksRoute: typeof AuthenticatedAppTasksRoute
  AuthenticatedAppTodayRoute: typeof AuthenticatedAppTodayRoute
  AuthenticatedAppWeekRoute: typeof AuthenticatedAppWeekRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppCategoriesRoute: AuthenticatedAppCategoriesRoute,
  AuthenticatedAppFocusRoute: AuthenticatedAppFocusRoute,
  AuthenticatedAppInboxRoute: AuthenticatedAppInboxRoute,
  AuthenticatedAppMonthRoute: AuthenticatedAppMonthRoute,
  AuthenticatedAppProjectsRoute: AuthenticatedAppProjectsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTasksRoute: AuthenticatedAppTasksRoute,
  AuthenticatedAppTodayRoute: AuthenticatedAppTodayRoute,
  AuthenticatedAppWeekRoute: AuthenticatedAppWeekRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
